### ISSUE TITLE
multi-sample setting

### ISSUE THREAD

**Issue by HelenaLC** [DavisLaboratory/hoodscanR#1]
Hey! Thanks for an easy-to use package - was a breeze to get running. Quick Q: is there any native support for multiple samples? E.g., say by SPE contains many replicates (more than one `sample_id` in the object) - shall I run the series of functions demoed in the vignette separately on each and somehow aggregate results, or is this being taken care of by each function already?

**Comment by ningbioinfo** [comment]
Hi @HelenaLC , yeah I would run the functions on each of them, since I'm assuming the coordinates of different samples from different slides would be messing with each other. Unless for some samples, they have a global coordinates and they are all from one slide, such as the TMA sections from different patient in some of the cosmx data I've seen (not in the published ones though). And I haven't design any looping or recognising multiple samples in functions, this is a good suggestion and may write it in the next release.

**Comment by HelenaLC** [comment]
Alright, thanks for clarifying. Yeah, I think it would be a good idea to implement this... nothing more than a `lapply` call really. But would make a lot of sense given that, e.g., `SpatialExperiment` forces `sample_id`s to exists for this exact same reason: that `spatialCoords` may overlap when multiple slides are stored in the same object. At least for CosMx's FoVs wouldn't be overlapping, though I agree that each should probably be considered separately. - Anyways, closing!

**Comment by vraghu90** [comment]
Has there been any progress on this? What is the recommended workflow to perform across multiple samples?
